# Generated by Django 5.2.1 on 2025-05-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAPIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('request_headers', models.JSONField(blank=True, null=True)),
                ('request_params', models.JSONField(blank=True, null=True)),
                ('response_status', models.IntegerField()),
                ('response_body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
